### PR TITLE
Wpml support

### PR DESCRIPTION
**Pull request by hermes3por3**
This has changes in `includes/core.php` and `includes/sitemaps.php` with WPML support.

### CODE REVIEW

**Comment by hermes3por3** [comment]
I am not familiar with the system. Should I leave it open or closed?

**Comment by RavanH** [comment]
Hi Hermes, just leave it open. Thanks for your contribution! I'll review the code and if all is well, it should make it into the next release :)

If I've any questions (about WPML for example) I'll post them here, OK?

**Comment by RavanH** [comment]
Can you share a link to a sitemap where WPML is active?

**Comment by hermes3por3** [comment]
Yes: http://www.slowbarcelona.es You can see sitemap in http://www.slowbarcelona.es/sitemap.xml

**Comment by RavanH** [comment]
Great!

I have two questions: 
1. Does WPML have an option to **not** include the language in the URL? I mean, could it have the english contact page http://www.slowbarcelona.es/en/home/contactus/ live on http://www.slowbarcelona.es/home/contactus/ for example? And if so, how would that scenario reflect on the sitemaps?
2. Could you switch on the Google News Sitemaps option so I can take a look at the news sitemap?

**Comment by RavanH** [comment]
Interesting case of WPML and empty sitemap reported here https://wordpress.org/support/topic/xml-sitemap-and-wpml-1 ... One language has no posts but the sitemap plugin cannot detect that in advance so it includes a post sitemap in the index. No idea how to address that. Is there any function in WPML that allows to detect the number of posts per language?

**Comment by hermes3por3** [comment]
Hi, I have upgraded you plugin to the latest version and introduced the same changes for WPML that are present in your branch WPML_compat. I activated the google news feed and now they can be reached at http://www.slowbarcelona.es/sitemap-news.xml and http://www.slowbarcelona.es/en/sitemap-news.xml without problems.

I do not know how to merge within github the commits you made in your master branch since I forked your plugin. Should I open a new pull request reintroducing the changes in WPML_compat branch, or is there a way to do it within github?

**Comment by hermes3por3** [comment]
Regarding the topic https://wordpress.org/support/topic/xml-sitemap-and-wpml-1 you can definitely check for posts (actually of each activated post_type) in any given language in WPML.  Does your code check for the presence posts of a specific post_type before creating the sitemap for that specific post type?

**Comment by RavanH** [comment]
Hi Hermes, no we can leave this pull request open for now. I'm currently trying to figure out a slightly different approach to see which one fits best with the current plugin setup. But whichever I decide, basic WPML support will come :)

> Regarding the topic https://wordpress.org/support/topic/xml-sitemap-and-wpml-1 you can definitely 
> check for posts (actually of each activated post_type) in any given language in WPML.

Is there a specific WPML function for that? If so, is there any public documentation?

> Does your code check for the presence posts of a specific post_type before creating the sitemap for > that specific post type?

Yes it does, but not "per language" only "per post type" or "per taxonomy term" as a whole because a sitemap is normally language neutral. This means that (for that example) if there are posts but they all are in one language, the check will tell my plugin that there _are_ posts while on the front end, when WPML has filtered out all posts in a language that the visitor has not chosen, there can be none.

I suppose WPML filters posts on the front-end based on either the visitors browser language, URL (containing language information) or active choice from the language menu. This is similar to how Polylang does it, but the difference is that currently WPML also filters posts from the sitemap. The result is that the main posts sitemap will only contain posts from the default language. This makes it necessary to add secondary language sitemaps like /en/sitemap.xml for example.

**Comment by hermes3por3** [comment]
Hi there was a problem with the new version (4.7.1) and WPML. While you were getting the posts in all languages using that `remove_filter` trick, the calls to `get_permalink` in your templates were outputting links in one language only (which means translated post urls were being displayed multiple times with the same url). I have resolved this and also another problem with taxonomies feeds, all minimal changes.

You can see it working well at http://www.slowbarcelona.es/sitemap.xml (taxonomies are not activated on my production server)

How can I fork your master branch again from github? Or how can I apply all your commits to my fork? I am not so familiar with github.

**Comment by RavanH** [comment]
> the calls to get_permalink in your templates were outputting links in one language only (which means translated post urls were being displayed multiple times with the same url). I have resolved this and also another problem with taxonomies feeds, all minimal changes.

That's great! Did you apply these changes to your WMPL-compat-2 branch? Can you create a merge request from that branch to my master branch?

**Comment by hermes3por3** [comment]
> That's great! Did you apply these changes to your WMPL-compat-2 branch?
Yes, I managed to commit all your updates to release 4.7.1 and then applied the changes I mentioned. I have created a pull request to your master branch. If I am not mistaken.

**Comment by hermes3por3** [comment]
Hi, I will review your updates in my site shortly and will let you know!

**Comment by RavanH** [comment]
Make sure you use the latest version 4.7.3 and let me know if you find any issues :)

**Comment by hermes3por3** [comment]
Hi, almost there! Now it lists correctly all the slugs in their language specific variations, but it does not prepend the language in the url. For example, if a url _not_ in the default language would be `http://www.slowbarcelona.es/en/cocktail/atari/` it is listed as `http://www.slowbarcelona.es/cocktail/atari/` instead. If you check http://www.slowbarcelona.es/sitemap.xml you will not find this problem because I am using an older and edited version of the plugin. The error I mentioned happens in my local installation with the latest plugin version (4.7.3). I haven't had time to go through the code to see where the problem is, though I would start in the `filter_request` method.

**Comment by RavanH** [comment]
Hmmm... still something. 

WPML is a nightmare (as I suspected) because every time I fix one thing another thing comes up or back. Another user reported that with version .3 the URLs where finally working correctly (with subdomains, I think it was) but apparently still not with subdirectories...

Thanks for the feedback!

**Comment by RavanH** [comment]
@hermes3por3 there is a new version (.4) ready in master https://github.com/RavanH/xml-sitemap-feed could you dowload the zip and test it please? :)

**Comment by hermes3por3** [comment]
Yeah, it works!

**Comment by RavanH** [comment]
Will be releasing the upgrade then :) thanks again for the feedback !

**Pull request closed without merging**
