### PR TITLE
Fix url for images : add URI if not present

### PR DESCRIPTION
**Pull request by EChaffraix**
There was a problem in Google search console : Url is not valid.

### CODE REVIEW

**Comment by RavanH** [comment]
Hi Emmanuel, thanks for chipping in! 

Could you tell me when/where/how the original issue occurred? I wonder in which cases wp_get_attachment_image_src() does not return a complete URI...

And next, if there might be cases where a protocol-less (starting with "//" so missing "http") or path-relative URI could occur. In which case, add_domain_if_needed() would return an invalid URI.

Thanks!

**Comment by gramorris** [comment]
Hi Ravan,

Late on this but was considering also doing a pull to solve this issue. There are themes that overwrite wp_get_attachment_image_src() to return relative urls. In this case the XML files coming out of the plugin are also relative and are marked as errors in webmaster tools.

There is a similar function in Yoast SEO called get_absolute_url() to take in to account the possibility of relative urls.

I would suggest this is a necessary feature to be added.

Thanks.

**Comment by RavanH** [comment]
Hi @gramorris thanks for that explanation. Is there a (free) theme that does this so I can test it? I wonder if a simple remove_all_filters() wouldn't be faster than rebuilding each filtered url...

**Comment by gramorris** [comment]
The two theme's we use have this issue but they are both paid for. I guess it depends what other filters are running as to whether remove_all_filters() just introduces more issues.

We did tweak the code to look for a leading forward slash rather than http, as you mentioned in your initial reply using http does exclude other protocols.

**Comment by RavanH** [comment]
Did commit https://github.com/RavanH/xml-sitemap-feed/commit/6213c523debf6227890270b42b7ed849d9e5ec63 which should fix this issue. If anyone could test, I'd be very happy to hear the results :)

**Comment by gramorris** [comment]
There's a bug in domain(), parse_url has the component parameter specified (returning a string) but ln 140 is expecting a returned array as if no component parameter was given. I suggest:

public function domain() {
		// allowed domain
		if ( empty($this->domain) ) {
			$url_parsed = parse_url( $this->home_url(), PHP_URL_HOST );
			$this->domain = str_replace("www.","",$url_parsed);
		}

		return $this->domain;
	}

**Comment by RavanH** [comment]
@gramorris How careless. I added the PHP_URL_HOST parameter without adapting the str_replace input. Sorry for the inconvenience and many thanks for the testing and feedback!

**Comment by gramorris** [comment]
not a problem @RavanH

**Comment by EChaffraix** [comment]
Hi, sorry @RavanH, I didn't notice your answer. I quitted my job and cannot give you the whole context .... You can close this PR, I am not sure it is still relevant.

**Comment by RavanH** [comment]
@EChaffraix no problem, thanks for your contribution :)

**Pull request closed without merging**
